@base_url=http://localhost:8000

### Obtener notas
GET {{base_url}}/notes


### Obtener notas filtradas
GET {{base_url}}/notes?category=frontend


### Obtener una nota
GET {{base_url}}/notes/68194a11c3ae9bccc143d847


### Crear una nota
# @name createNote
POST {{base_url}}/notes
Content-type: application/json

{
    "content": "MySql es una base de datos relacional.",
    "categories":["bases de datos"],
    "rate":6.8
}

### Guardar el id de la respuesta
@noteID = {{createNote.response.body.id}}

### Actualizar una nota
PATCH {{base_url}}/notes/{{noteID}}
Content-type: application/json

{ 
    "rate":8.0,
    "important":false
}

### Borrar una pelicula
DELETE {{base_url}}/notes/{{noteID}}
