@base_url=http://localhost:8000/notes

### Obtener notas
GET {{base_url}}


### Obtener notas filtradas
GET {{base_url}}?category=Programación


### Obtener una nota
GET {{base_url}}/1


### Crear una nota
POST {{base_url}}
Content-type: application/json

{
    "content": "MySql es una base de datos relacional.",
    "category":["Base de dato"]
}


### Actualizar una nota
PATCH {{base_url}}/1
Content-type: application/json

{
    "important":false
}


### Borrar una pelicula
DELETE {{base_url}}/5